# Generated by Django 5.1.6 on 2025-03-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('eid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('oid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('correctness', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('grade', models.IntegerField(verbose_name=10)),
                ('gender', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('aid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.options')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('qid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.exams')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.quizs'),
        ),
        migrations.CreateModel(
            name='AnalyzeModel',
            fields=[
                ('analyze_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.answers')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.exams')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.options')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.quizs')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
    ]
